version: '3.7'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: mauricedb
      POSTGRES_USER: maurice
      POSTGRES_PASSWORD: 123maurice
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
    networks:
      - web

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - web

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgresdb
    networks:
      - web

  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8090:80"
      - "81:81"
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    driver: bridge
